* ColorNote backup decryptor 
  [[https://www.colornote.com/][ColorNote]] (shookingly..) don't support any kind of export[1] and the backup format is both proprietary and encrypted using a undocumented method.
  
  UPDATE: It seems to be easy to get hold of the raw sqlite database using adb: https://stackoverflow.com/questions/13006315/how-to-access-data-data-folder-in-android-device/17876731#17876731

  This tool will decrypt your auto backup (passwd: 0000) files to json format.

  I've included a prebuild jar for convenience.

  Let me know if you need help getting it to work. This was thrown together for my own need and is not polished and user friendly. It's only tested on very old backup file.

*** Usage
    The script expects input on stdin. It outputs something that's almost json. A fixup script is provided that fixes the remaining weirdness.
    #+BEGIN_SRC shell-script
    java -jar < *-AUTO.dat | fixup > notes.json
    # Optional
    jq --raw-output '[.created_date, .modified_date, .title, .note] | @csv' < notes.json > notes.cvs
    #+END_SRC


[1] https://www.colornote.com/faq-question/can-i-read-a-colornote-note-in-other-word-processing-programs/
*** Alternative method
    If you have root access you can get hold of the sqlite db directly: http://danyilbohdan.com/blog/colornote/ 

    I haven't tried it myself, but someone suggested that you could restore the backup in an emulator if you don't have a rooted phone.
